name: Test

on:
  push:
    branches:
      - master  # adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
     - uses: actions/setup-node@v3
  with: 
    node-version: 16

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: npm test
